/* Does LaZer's verifier reject a DEGENERATE WITNESS?
 *
 * This is the question bead corpus-no-degenerate-witness-class-piz6 exists for. The
 * 64-vector corpus has 25 reject vectors and NOT ONE of them is a degenerate witness,
 * so the gate we have been treating as the soundness discriminator cannot see the one
 * bug class we have proven twice in our own consensus code:
 *   - LatticeFold+ EvalCheckFoldProof  (memory latticefold-zero-witness-forgery-2026-08-12)
 *   - LatticeRangeProofV2              (bead zero-witness-range-verifier-iebb)
 * In both, every accept-path check is HOMOGENEOUS in the witness, so witness = 0
 * satisfies all of them, and the only non-homogeneous check is a Fiat-Shamir seed the
 * attacker reads off public data and plants.
 *
 * It matters now because option 4 adopts LaZer's verifier as consensus code. If LaZer
 * shares the defect, extraction inherits a forgery AND the corpus certifies it 64/64,
 * because the corpus's expected verdicts were generated by LaZer itself.
 *
 * Reuses kat_verify.c wholesale (statement assembly must be call-for-call identical to
 * the reference, per PHASE2-FINDINGS.md) by suppressing its main.
 */
#define main kat_verify_main_unused
#include "kat_verify.c"
#undef main

/* ------------------------------------------------------------------ mutants -- */

enum mutant {
    M_BASELINE = 0,   /* untouched: must ACCEPT, else the harness itself is broken   */
    M_ALLZERO,        /* whole payload zeroed: the exact shape of our proven forgery */
    M_ZERO_KEEP_HEAD, /* zero everything after the first 32 bytes                    */
    M_ZERO_TAIL,      /* zero the trailing half (witness fields live late)           */
    M_SCALE2,         /* every byte doubled mod 256: a NON-ZERO member of the class  */
    M_ONES,           /* all 0xff: degenerate but maximal rather than minimal        */
    M_COUNT
};

static const char *mutant_name(enum mutant m)
{
    switch (m) {
    case M_BASELINE:      return "baseline (untouched)";
    case M_ALLZERO:       return "all-zero payload";
    case M_ZERO_KEEP_HEAD:return "zero after byte 32";
    case M_ZERO_TAIL:     return "zero trailing half";
    case M_SCALE2:        return "scaled x2 (NON-ZERO)";
    case M_ONES:          return "all 0xff";
    default:              return "?";
    }
}

static void apply_mutant(enum mutant m, uint8_t *p, size_t n)
{
    switch (m) {
    case M_BASELINE:
        break;
    case M_ALLZERO:
        memset(p, 0, n);
        break;
    case M_ZERO_KEEP_HEAD:
        if (n > 32) memset(p + 32, 0, n - 32);
        break;
    case M_ZERO_TAIL:
        memset(p + n / 2, 0, n - n / 2);
        break;
    case M_SCALE2:
        for (size_t i = 0; i < n; i++) p[i] = (uint8_t)(p[i] * 2u);
        break;
    case M_ONES:
        memset(p, 0xff, n);
        break;
    default:
        break;
    }
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <corpus-dir>\n", argv[0]);
        return 2;
    }
    const char *dir = argv[1];

    /* Same init path the gate uses. lazer_init() is NOT optional - omitting it
     * segfaults before the first verify, which is a harness bug and must not be
     * mistaken for the documented verify-path SEGV. */
    setvbuf(stdout, NULL, _IONBF, 0);
    lazer_init();
    build_range_A();

    char path[512];
    snprintf(path, sizeof(path), "%s/range.jsonl", dir);
    FILE *f = fopen(path, "r");
    if (!f) die("cannot open range.jsonl");

    printf("=== DEGENERATE-WITNESS PROBE vs LaZer _lin_verifier_verify ===\n");
    printf("entry point: lin_verifier_verify (identical to the corpus gate)\n\n");

    char *line = NULL;
    size_t cap = 0;
    ssize_t got;
    int probed = 0, unexpected_accepts = 0, baseline_fail = 0;

    while ((got = getline(&line, &cap, f)) > 0) {
        if (got < 8) continue;
        size_t l;
        const char *exp = json_str(line, "expect", &l);
        if (!exp || strncmp(exp, "accept", 6) != 0)
            continue; /* mutate only vectors that legitimately verify */
        const char *id = json_str(line, "id", &l);
        char idbuf[64] = "?";
        if (id) { size_t c = l < 63 ? l : 63; memcpy(idbuf, id, c); idbuf[c] = 0; }

        /* only the plain range vectors carry a bare "c" statement */
        size_t hl;
        const char *ch = json_str(line, "c", &hl);
        if (!ch) continue;

        size_t phl;
        const char *ph = json_str(line, "proof", &phl);
        if (!ph) continue;
        size_t prooflen;
        uint8_t *orig = hex_decode(ph, phl, &prooflen);
        if (!orig) die("bad proof hex");

        int64_t *cc = decode_stmt(ch, hl, 8);

        printf("vector %-16s proof=%zu bytes\n", idbuf, prooflen);
        for (enum mutant m = 0; m < M_COUNT; m++) {
            uint8_t *p = malloc(prooflen);
            memcpy(p, orig, prooflen);
            apply_mutant(m, p, prooflen);

            polyvec_t t;
            polyvec_alloc(t, Rp, 8);
            range_statement_t(t, cc);
            int accept = verify_one(A_range, t, range_params, p, prooflen);
            polyvec_free(t);
            free(p);

            int want_accept = (m == M_BASELINE);
            const char *tag;
            if (want_accept)
                tag = accept ? "ok" : "*** BASELINE BROKEN ***";
            else
                tag = accept ? "*** ACCEPTED - FORGERY ***" : "rejected (good)";
            printf("    %-24s -> %-8s %s\n", mutant_name(m),
                   accept ? "ACCEPT" : "reject", tag);

            if (want_accept && !accept) baseline_fail++;
            if (!want_accept && accept) unexpected_accepts++;
            probed++;
        }
        printf("\n");
        free(orig);
        free(cc);
    }
    free(line);
    fclose(f);

    printf("=== RESULT ===\n");
    printf("probes run:            %d\n", probed);
    printf("baseline failures:     %d\n", baseline_fail);
    printf("degenerate ACCEPTS:    %d\n", unexpected_accepts);
    if (baseline_fail) {
        printf("VERDICT: INCONCLUSIVE - the harness cannot verify honest proofs.\n");
        return 3;
    }
    if (unexpected_accepts) {
        printf("VERDICT: LAZER ACCEPTS A DEGENERATE WITNESS. Third instance of the\n");
        printf("         class, in the code option 4 would adopt. G1 must be re-decided.\n");
        return 1;
    }
    printf("VERDICT: LaZer rejected every degenerate mutant tested.\n");
    printf("NOTE the scope of that claim: these are BYTE-LEVEL mutants. They do NOT\n");
    printf("     include the full planted-challenge attack, which needs the prover-side\n");
    printf("     encoder to build a self-consistent zero-witness blob. The analytical\n");
    printf("     reason that attack fails is lnp-quad.c:455-478 -- v = z*R2*z + c*r1*z\n");
    printf("     + c^2*r0 - f is ABSORBED INTO the challenge derivation rather than\n");
    printf("     compared against zero, so with a zero witness v = c^2*r0 and a forger\n");
    printf("     needs c = F(H(... c^2*r0 ...)), a hash FIXED POINT. That is the check\n");
    printf("     our two broken verifiers lack, and it is what extraction must preserve.\n");
    return 0;
}
