#!/usr/bin/env python3
"""Fixture corpus for register-lint.py. Offline: it builds its own event payload and stubs
the API call.

The first negative cases are texts that were published from this repository before the check
existed. The rest were written to pin one pattern each, so that no pattern can be removed
while this corpus still reports that every fixture behaves. Every positive case is one a
check has to let through, and each cost something before it did: a review bot's prose, and a
commit message naming the manifest file it changes.
"""
import importlib.util
import json
import os
import shutil
import sys
import tempfile

# Loading the checker by path would otherwise leave a __pycache__ directory beside it, in a
# directory this repository tracks.
sys.dont_write_bytecode = True

_spec = importlib.util.spec_from_file_location(
    "lint", os.path.join(os.path.dirname(os.path.abspath(__file__)), "register-lint.py"))
mod = importlib.util.module_from_spec(_spec)
# SystemExit is caught alongside Exception because a checker carrying `sys.exit(0)` at module
# scope raises it here, and letting that propagate would end this corpus with the exit status
# of a clean run and no output at all. Naming the two leaves KeyboardInterrupt to the shell.
try:
    _spec.loader.exec_module(mod)
except (SystemExit, Exception) as _exc:
    print(f"FAIL | the checker does not import | {type(_exc).__name__}: {_exc}")
    sys.exit(1)
for _name in ("lint", "lint_path", "main"):
    if not callable(getattr(mod, _name, None)):
        print(f"FAIL | the checker has no callable {_name}()")
        sys.exit(1)

TEXTS = [
    # (name, text, must_fail)
    ("a body in register", "Closes the double payment. Costs 44 us per address on loopback.", False),
    ("a generated-by footer", "Closes item 5.\n\n\U0001F916 Generated with Claude Code\n", True),
    ("a co-author trailer", "utxo: persist errors\n\nCo-Authored-By: someone <a@b.c>", True),
    ("a generated-by trailer", "Closes item 5.\n\nGenerated-by: some-tool 1.2\n", True),
    ("a generated-by footer sentence", "Closes item 5.\n\nGenerated by some-tool.\n", True),
    ("a generated-by footer behind a marker", "Closes item 5.\n\n> • generated by a tool\n", True),
    ("'generated by' inside a sentence is ordinary prose",
     "The cache holds the address generated by the derivation, and the record advances.", False),
    ("a review round named in a body", "Round 1 review (clean-room): nothing blocks.", True),
    ("review triage vocabulary", "Four should-fix items, all addressed.", True),
    ("a release train named in a body", "Rides the soak clock as a freeze candidate.", True),
    ("an em dash in prose", "The reader sees the diff — the whole of it.", True),
    ("the X, not Y tic", "A stale cache is an outage, not an absence of deposits.", True),
    ("a filler adjective", "A comprehensive rewrite of the connection layer.", True),
    ("a figurative verb applied to code", "A refused address does not starve the reconcile.", True),
    ("a commit message naming the file it changes",
     "scripts: declare the guards\n\nEach change is declared in scripts/mutants.json, and "
     "check-mutants.py asks whether one test catches it.", False),
    ("a title in register", "withdraw: one intent builds one transaction", False),
    # One fixture per pattern below. The fixtures above each trip several patterns at once,
    # so removing any one of them left the fixture failing for a different reason and the
    # corpus noticed nothing. register-pin-selftest.py is what keeps this list complete.
    ("the vendor footer wording", "The summary was generated with the exporter.", True),
    ("the robot marker", "Closes item 5.\n\n\U0001F916\n", True),
    ("a vendor name, claude", "This body names claude.", True),
    ("a vendor name, anthropic", "This body names anthropic.", True),
    ("a vendor name, gemini", "This body names gemini.", True),
    ("a vendor name, chatgpt", "This body names chatgpt.", True),
    ("a vendor attribution, copilot", "The body says copilot wrote the helper.", True),
    ("a reading named as clean-room", "The reading was clean-room.", True),
    ("a numbered round", "The finding came from round 2.", True),
    ("a spelled round", "The finding came from round two.", True),
    ("the phrase review round", "The change survived a review round.", True),
    ("review triage, nits", "Two nits remain.", True),
    ("a merge verdict", "Nothing here blocks merge.", True),
    ("a clean verdict", "On this reading nothing blocks.", True),
    ("a numbered gate", "This is gate 9.", True),
    ("release eligibility", "The work is post-freeze-eligible.", True),
    ("a fleet artifact", "The binary is a fleet artifact.", True),
    ("the soak clock", "It rides the soak clock.", True),
    ("an absent soak", "The change went in with no soak.", True),
    ("a freeze candidate", "The tag is a freeze candidate.", True),
    ("a session attribution", "The defect is introduced-this-session.", True),
    ("a pre-existing gap", "This is a pre-existing gap.", True),
    ("a definition of done", "It meets the definition-of-done.", True),
    ("an earlier draft", "An earlier draft said otherwise.", True),
    ("a previous attempt", "The previous attempt failed.", True),
    ("a pointer into the body", "The reason is in the pr body.", True),
    ("an instruction to read the body", "See the pr body for the reason.", True),
    ("a filler phrase", "It's worth noting that the cache is shared.", True),
    ("a metaphor for a literal phrase", "The check was blind to the empty case.", True),
    # Every fixture above is short, so a lint() that reads only the start of a text would
    # pass all of them and miss a trailer at the foot of a real body.
    ("a trailer at the end of a body of ordinary length",
     "The deposit reconciler reads the confirmed set once per interval and compares it "
     "against the set it recorded on the pass before. Addresses that gained a confirmation "
     "move to the settled table, and addresses that lost one return to the pending table. "
     "The interval is configurable and the default is thirty seconds."
     "\n\nCo-Authored-By: a <a@b.c>", True),
]

PATHS = [
    ("an ordinary test path", "deposit/final_set_staleness_and_errors_test.go", False),
    ("a path named for a review round", "deposit/final_set_round2_test.go", True),
    ("a path named for a review round, underscore", "electrumx/round_2_test.go", True),
    ("a path with a number that is not a round", "crypto/mldsa44_test.go", False),
    ("a source path", "withdraw/engine.go", False),
    ("a path named clean-room", "deposit/cleanroom_test.go", True),
    ("a path named for a review round, spelled", "deposit/review_round_test.go", True),
    ("a path named for triage", "deposit/shouldfix_test.go", True),
    ("a path named pre-existing", "deposit/preexisting_test.go", True),
    ("a path naming the session", "deposit/introduced_this_session_test.go", True),
]

bad = 0
for name, text, must_fail in TEXTS:
    failed = bool(mod.lint(text))
    ok = failed == must_fail
    bad += 0 if ok else 1
    print(("PASS" if ok else "FAIL"), "|", name, "|", "finding" if failed else "clean",
          "" if ok else f"| {mod.lint(text)}")
for name, path, must_fail in PATHS:
    failed = bool(mod.lint_path(path))
    ok = failed == must_fail
    bad += 0 if ok else 1
    print(("PASS" if ok else "FAIL"), "|", name, "|", "finding" if failed else "clean",
          "" if ok else f"| {mod.lint_path(path)}")

# A pull request's commits and its files each arrive a page at a time, and the API sends 30
# items unless asked for more. A checker that reads the first page and stops prints "no
# findings" over text it never read, and the count it prints alongside hides that. This is a
# defect the check shipped with: a pull request of 33 files was reported clean by a checker
# that had read 30 of its paths.
LINKS = [
    ("a next link among the others",
     '<https://api.github.com/x?page=3>; rel="prev", <https://api.github.com/x?page=5>; rel="next"',
     "https://api.github.com/x?page=5"),
    ("the last page offers no next link",
     '<https://api.github.com/x?page=1>; rel="first", <https://api.github.com/x?page=4>; rel="prev"',
     None),
    ("a response whose link header is empty", "", None),
    ("a response with no link header", None, None),
]

for name, header, want in LINKS:
    got = mod.next_page(header)
    ok = got == want
    bad += 0 if ok else 1
    print(("PASS" if ok else "FAIL"), "|", name, "| next page", got,
          "" if ok else f"| expected {want}")


class _Page:
    """One response, with the two things api() takes from it: a body and the headers."""

    def __init__(self, items, link=""):
        self._body = json.dumps(items).encode()
        self.headers = {"Link": link}

    def read(self, *_):
        return self._body

    def __enter__(self):
        return self

    def __exit__(self, *_):
        return False


class _FakeRequest:
    """urllib.request, holding the two names api() calls and the urls it asked for."""

    def __init__(self, pages):
        self.pages = pages
        self.urls = []

    def Request(self, url, headers=None):
        self.urls.append(url)
        return url

    def urlopen(self, req, timeout=None):
        return self.pages.pop(0)


_fake = _FakeRequest([_Page([{"sha": "a" * 40}], '<https://api.github.com/page2>; rel="next"'),
                      _Page([{"sha": "b" * 40}])])
_real_urllib, mod.urllib = mod.urllib, type("_FakeUrllib", (), {"request": _fake})
os.environ["GITHUB_TOKEN"] = "fixture"
try:
    _items = mod.api("repos/owner/repo/pulls/1/commits")
finally:
    mod.urllib = _real_urllib

API = [
    ("both pages of a list endpoint are read", len(_items), 2),
    ("the second request is the url the first response gave",
     _fake.urls[-1], "https://api.github.com/page2"),
    ("the first request asks for a full page", "per_page=100" in _fake.urls[0], True),
]

for name, got, want in API:
    ok = got == want
    bad += 0 if ok else 1
    print(("PASS" if ok else "FAIL"), "|", name, "|", got, "" if ok else f"| expected {want}")

# lint() deciding correctly is not the same as the check failing. main() is what turns a
# finding into an exit status, and what decides whose text counts as ours. A checker whose
# lint() is intact and whose main() returns 0 on findings prints every error and passes.
# These run main() against a review event, which reads the event file and calls no API.
COMMENTS = [
    ("a comment of ours, with a finding", "someone", "User",
     "x\n\nCo-Authored-By: a <a@b.c>", 1),
    ("a comment of ours, clean", "someone", "User",
     "withdraw: one intent builds one transaction", 0),
    ("a comment from a bot, with a finding", "some-bot", "Bot",
     "x\n\nCo-Authored-By: a <a@b.c>", 0),
]

# main() handles three comment events in one branch, and a checker can return early on any
# one of them. issue_comment is the one that carries a body edited in the web interface and
# a comment posted from a phone, which is a reason this check runs on the platform at all.
COMMENT_EVENTS = [
    ("pull_request_review", "review"),
    ("issue_comment", "comment"),
    ("pull_request_review_comment", "comment"),
]

CLEAN = "withdraw: one intent builds one transaction"
DIRTY = "x\n\nCo-Authored-By: a <a@b.c>"

# The pull request branch of main() reads four kinds of text, and a checker that drops any
# one of them keeps every fixture above behaving. One event per kind, each with the finding
# in a different place.
#
# Each runs under both event names that reach this branch. The required job fires on
# pull_request_target and the cross-run job on pull_request, so a checker that returns early
# on one of the two names would leave every case here behaving and one job checking nothing.
PULL_EVENTS = ["pull_request", "pull_request_target"]
PULLS = [
    ("a pull request title with a finding", DIRTY, CLEAN, CLEAN, "withdraw/engine.go", 1),
    ("a pull request body with a finding", CLEAN, DIRTY, CLEAN, "withdraw/engine.go", 1),
    ("a commit message with a finding", CLEAN, CLEAN, DIRTY, "withdraw/engine.go", 1),
    ("a changed path with a finding", CLEAN, CLEAN, CLEAN, "deposit/round2_test.go", 1),
    ("a pull request with nothing in it", CLEAN, CLEAN, CLEAN, "withdraw/engine.go", 0),
]

env_tmp = tempfile.mkdtemp(prefix="register-corpus-")


def _verdict(name, want):
    """Run main() under the event already written, and report what it returned."""
    global bad
    try:
        got = mod.main()
    # A checker that exits or raises is not a passing checker. SystemExit is named because a
    # checker can call sys.exit() instead of returning, and an interrupt is left to the shell.
    except (SystemExit, Exception) as exc:
        got = f"raised {type(exc).__name__}"
    ok = got == want
    bad += 0 if ok else 1
    print(("PASS" if ok else "FAIL"), "|", name, "| main() returned", got,
          "" if ok else f"| expected {want}")


def _event(payload, event_name):
    path = os.path.join(env_tmp, "event.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh)
    os.environ["GITHUB_EVENT_PATH"] = path
    os.environ["GITHUB_REPOSITORY"] = "owner/repo"
    os.environ["GITHUB_EVENT_NAME"] = event_name


for event_name, key in COMMENT_EVENTS:
    for name, login, kind, body, want in COMMENTS:
        _event({key: {"body": body, "user": {"login": login, "type": kind}}}, event_name)
        _verdict(f"{name}, on {event_name}", want)

for event_name in PULL_EVENTS:
    for name, title, body, message, path, want in PULLS:
        _event({"pull_request": {"number": 1, "title": title, "body": body}}, event_name)
        # Stand in for the two API reads. A checker that reaches the network instead of
        # calling api() finds no token and raises, which _verdict reports as a failure.
        mod.api = lambda p, _m=message, _p=path: (
            [{"sha": "0" * 40, "commit": {"message": _m}}] if p.endswith("/commits")
            else [{"filename": _p}])
        _verdict(f"{name}, on {event_name}", want)

shutil.rmtree(env_tmp, ignore_errors=True)

total = (len(TEXTS) + len(PATHS) + len(LINKS) + len(API)
         + len(COMMENTS) * len(COMMENT_EVENTS) + len(PULLS) * len(PULL_EVENTS))
print(f"\n{total - bad}/{total} fixtures behave")
sys.exit(1 if bad else 0)
