#!/usr/bin/env python3
"""Check that a pull request's own text reads the way this repository's text is meant to.

This runs on the platform rather than on a contributor's machine, so it holds for a body
edited in the web interface, a comment posted from a phone, and a commit pushed by any tool.
It reads the event payload and the pull request's files, and reads nothing else.

It checks three things:

  attribution   a generated-by footer or a co-author trailer in any published text
  narrative     internal review vocabulary: which review round a change came from, what a
                reviewer graded it, what release train it rode. A reader of this repository
                needs the change and the reason; the path it took to get here is noise.
  register      the mechanical writing tells: an em dash in prose, filler adjectives, the
                "X, not Y" tic, a figurative verb applied to code

It also checks changed PATHS for the same narrative vocabulary. A file name outlives the
review that produced it: it stays in the tree, in every URL, and in every later stack trace.

Texts written by someone else are reported and do not fail the check. A review bot's prose is
not ours to rewrite, and a check that fails on it would be turned off within a week.

Exit 1 on a finding in our own text, 0 otherwise.
"""
import json
import os
import re
import sys
import urllib.error
import urllib.request

ATTRIBUTION = [
    r"co-authored-by",
    r"generated with",
    # A generated-by footer or trailer, in any of its shapes: "Generated-by: tool",
    # "Generated by tool", the same behind an emoji or a markdown marker. Anchored to the
    # start of a line, because "the address generated by the derivation" is ordinary prose
    # in this repository and a check that refuses it would teach people to skip the check.
    r"(?m)^[\s\W]*generated[- ]by\b",
    r"\U0001F916",
    r"\bclaude\b", r"\banthropic\b", r"\bgemini\b", r"\bchatgpt\b", r"\bcopilot wrote\b",
]

NARRATIVE = [
    r"clean[- ]room", r"\bround \d\b", r"\bround (one|two|three)\b", r"review round",
    r"should[- ]fix", r"\bnits?\b", r"blocks merge", r"nothing blocks",
    r"gate \d+\b", r"post[- ]freeze[- ]eligible",
    r"fleet artifact", r"soak clock", r"no soak", r"freeze candidate",
    r"introduced[- ]this[- ]session", r"pre[- ]existing gap", r"definition[- ]of[- ]done",
    r"an earlier draft", r"the previous (draft|round|attempt)",
    r"in the pr body", r"see the pr body",
]

REGISTER = [
    (r"—", "em dash in prose; use a comma, a colon, or two sentences"),
    (r"\b(comprehensive|robust|leverage|streamline|delve|facilitate|utilize|seamless|holistic)\b",
     "filler adjective"),
    (r"it'?s worth noting", "filler phrase"),
    (r",\s+not\s+\S", "the 'X, not Y' tic; end the sentence at X"),
    (r"\b(starv\w+|breath\w+|marri\w+|betray\w+|deserv\w+)\b", "figurative verb applied to code"),
    (r"\b(is|are|was|were) blind to\b", "metaphor where a literal phrase is available"),
]

PATHS = [
    r"round[-_ ]?\d", r"clean[-_ ]?room", r"review[-_ ]?round",
    r"should[-_ ]?fix", r"pre[-_ ]?existing", r"introduced[-_ ]this[-_ ]session",
]

# A file name is not prose: a message has to be able to name the file it changes.
FILENAME = re.compile(r"[\w./-]+\.(?:py|json|go|md|sh|yml|yaml|toml|txt|mod|sum)\b")


def hits(patterns, text):
    return [m.group(0) for m in (re.search(p, text, re.IGNORECASE) for p in patterns) if m]


def lint(text):
    prose = FILENAME.sub(" ", text)
    found = []
    for label, got in (("attribution", hits(ATTRIBUTION, text)),
                       ("narrative", hits(NARRATIVE, prose))):
        if got:
            found.append((label, got))
    reg = [what for pat, what in REGISTER if re.search(pat, prose, re.IGNORECASE)]
    if reg:
        found.append(("register", reg))
    return found


def lint_path(path):
    got = [p for p in PATHS if re.search(p, path, re.IGNORECASE)]
    return [("narrative in a path", got)] if got else []


# The next page of a paginated response, as the API names it in the Link header.
NEXT = re.compile(r'<([^>]+)>;\s*rel="next"')


def next_page(link_header):
    m = NEXT.search(link_header or "")
    return m.group(1) if m else None


def api(path):
    """Every item of a list endpoint, following the Link header to the last page.

    Both endpoints this checker reads are paginated and default to 30 items. Reading one page
    and stopping does not report a short pull request incorrectly; it reports a long one as
    clean while its later commits and files were never read.
    """
    url = f"https://api.github.com/{path}?per_page=100"
    items = []
    while url:
        req = urllib.request.Request(
            url,
            headers={"Accept": "application/vnd.github+json",
                     "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
                     "X-GitHub-Api-Version": "2022-11-28"})
        with urllib.request.urlopen(req, timeout=30) as r:
            page = json.load(r)
            link = r.headers.get("Link", "")
        # `items += page` on an object would extend the list with its keys and read as a
        # short answer rather than as an error.
        if not isinstance(page, list):
            raise TypeError(f"{path} answered with a {type(page).__name__} where this reads "
                            f"a list of items")
        items += page
        url = next_page(link)
    return items


def is_bot(user):
    return bool(user) and user.get("type") == "Bot"


def main():
    with open(os.environ["GITHUB_EVENT_PATH"], encoding="utf-8") as fh:
        event = json.load(fh)
    repo = os.environ["GITHUB_REPOSITORY"]
    name = os.environ.get("GITHUB_EVENT_NAME", "")

    texts, foreign, paths = [], [], []
    if name in ("issue_comment", "pull_request_review_comment", "pull_request_review"):
        node = event.get("comment") or event.get("review") or {}
        where = f"{name} by {(node.get('user') or {}).get('login')}"
        (foreign if is_bot(node.get("user")) else texts).append((where, node.get("body") or ""))
    else:
        pr = event.get("pull_request") or {}
        num = pr.get("number")
        texts.append(("the pull request title", pr.get("title") or ""))
        texts.append(("the pull request body", pr.get("body") or ""))
        for c in api(f"repos/{repo}/pulls/{num}/commits"):
            texts.append((f"commit {c['sha'][:7]}", c["commit"]["message"]))
        paths = [f.get("filename") or "" for f in api(f"repos/{repo}/pulls/{num}/files")]

    findings = []
    for where, text in texts:
        findings += [(where, label, got) for label, got in lint(text)]
    for path in paths:
        findings += [(f"path {path}", label, got) for label, got in lint_path(path)]

    for where, label, got in findings:
        print(f"::error title=Register check::{where}: {label}: {got}")
    for where, text in foreign:
        for label, got in lint(text):
            print(f"::notice title=Register check::{where} is not ours; reported, not failed: "
                  f"{label}: {got}")

    if findings:
        print(f"\n{len(findings)} finding(s). Correct the text and push, or edit the pull request.")
        return 1
    print(f"checked {len(texts)} texts and {len(paths)} paths, no findings; "
          f"{len(foreign)} foreign texts noted")
    return 0


if __name__ == "__main__":
    sys.exit(main())
