# Soqucoin Testnet Configuration
testnet=1
server=1
daemon=1
listen=1

# Network
# Allow RPC from localhost
rpcallowip=127.0.0.1
# Allow RPC from L7 Antminer (Local Network)
rpcallowip=192.168.1.235
# Allow RPC from entire local subnet (optional, for easier debugging)
rpcallowip=192.168.1.0/24

# Credentials
rpcuser=soquuser
rpcpassword=soqupassword
rpcbind=127.0.0.1
checkpoints=0


# Monitoring & Debugging
debug=net
debug=rpc
debug=bench
debug=pow

# Performance
dbcache=450
par=2
dnsseed=0
