#!/bin/bash
# Soqucoin Testnet3 Genesis Block Display - For social media screenshot
clear

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}███████╗ ██████╗  ██████╗ ██╗   ██╗ ██████╗ ██████╗ ██╗███╗   ██╗${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}██╔════╝██╔═══██╗██╔═══██╗██║   ██║██╔════╝██╔═══██╗██║████╗  ██║${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}███████╗██║   ██║██║   ██║██║   ██║██║     ██║   ██║██║██╔██╗ ██║${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}╚════██║██║   ██║██║▄▄ ██║██║   ██║██║     ██║   ██║██║██║╚██╗██║${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}███████║╚██████╔╝╚██████╔╝╚██████╔╝╚██████╗╚██████╔╝██║██║ ╚████║${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}╚══════╝ ╚═════╝  ╚══▀▀═╝  ╚═════╝  ╚═════╝ ╚═════╝ ╚═╝╚═╝  ╚═══╝${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${PURPLE}THE WORLD'S FIRST HIGH-PERFORMANCE QUANTUM-RESISTANT SCRIPT BLOCKCHAIN${NC}         ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}                                                                      ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}   ${GREEN}████████╗███████╗███████╗████████╗███╗   ██╗███████╗████████╗${NC}       ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}   ${GREEN}╚══██╔══╝██╔════╝██╔════╝╚══██╔══╝████╗  ██║██╔════╝╚══██╔══╝${NC}       ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}   ${GREEN}   ██║   █████╗  ███████╗   ██║   ██╔██╗ ██║█████╗     ██║${NC}         ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}   ${GREEN}   ██║   ██╔══╝  ╚════██║   ██║   ██║╚██╗██║██╔══╝     ██║${NC}         ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}   ${GREEN}   ██║   ███████╗███████║   ██║   ██║ ╚████║███████╗   ██║${NC}         ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}   ${GREEN}   ╚═╝   ╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝   ╚═╝${NC}         ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}                            ${WHITE}VERSION 3${NC}                              ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓${NC}                                                                      ${YELLOW}▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓${NC}       ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}GENESIS BLOCK #0${NC}                                  ${GREEN}✓ VERIFIED${NC}                 ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ──────────────────────────────────────────────────────────────────────────      ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}Block Hash (SHA256d):${NC}                                                         ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}cde63e00ef4c268af3bb351e2f7c9f4a2cbb21ec9f3d989e2c6594df810b7594${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}PoW Hash (Scrypt):${NC}                                                            ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${WHITE}000001cf9dfb272cb071d8490aa5a1108897de05bfa4b95f48097a2d4f0e7809${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}Timestamp:${NC}          ${WHITE}December 27, 2025 - 05:31:20 UTC${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}Difficulty:${NC}         ${WHITE}0.000244140625${NC}                                           ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}Chain Work:${NC}         ${WHITE}0x100010${NC}                                                 ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${YELLOW}Coinbase Message:${NC}                                                             ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${PURPLE}\"First quantum-resistant Scrypt chain - Soqucoin Testnet3 Dec 2025\"${NC}          ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${GREEN}⚡ POST-QUANTUM CRYPTOGRAPHY${NC}                                                 ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • Dilithium ML-DSA-44 (NIST FIPS 204)                                      ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • Bulletproofs++ Range Proofs                                              ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • PAT Signature Aggregation                                                ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • LatticeFold+ Recursive SNARKs                                            ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${GREEN}⛏️  MINING STATUS${NC}                                                              ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • Algorithm: Scrypt (ASIC Compatible)                                      ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • L3/L7/MiniDoge Mining: ${GREEN}ACTIVE${NC}                                            ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}      • Block Reward: 10,000 SOQ                                                 ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                                                    ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "   ${WHITE}soqucoin-cli -testnet getblockchaininfo${NC}"
echo -e "   ${GREEN}Chain status: OPERATIONAL | RPC: READY | Miners: CONNECTED${NC}"
echo ""
